FROM velero/velero-plugin-for-aws:v1.1.0

RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*

RUN adduser -h /home/velero-aws -s /bin/sh -u 1001 -D velero-aws
USER velero-aws
ENV HOME /home/velero-aws
